// Magasin d'un commerce. Modale d'édition par magasin : showModal(Config_Modal_Magasin, "edit", { id: magasin.id })
export const Config_Modal_Magasin = {
  id: {
    default: "Modal",
    add: "Modal_Add_Magasin",
    edit: "Modal_Edit_Magasin_$local-id",
  },
  title: {
    default: "Modal",
    add: "Ajouter un magasin",
    edit: "Modifier le magasin",
  },
  success: {
    default: "Succès",
    add: "Magasin ajouté avec succès.",
    edit: "Magasin modifié avec succès.",
    delete: "Magasin supprimé avec succès.",
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de l'ajout du magasin.",
    edit: "Erreur lors de la modification du magasin.",
  },
  champs: [
    {
      name: "title",
      label: "Nom",
      description: null,
      placeholder: "Nom du magasin",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "description",
      label: "Description",
      description: null,
      placeholder: "Description du magasin",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "founded_date",
      label: "Date d'ouverture dans le RP",
      description: "",
      placeholder: "",
      type: "date",
      defaultValue: new Date().toISOString().split("T")[0],
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "dimension_id",
      label: "Dimension",
      description: null,
      placeholder: "Dimension du magasin",
      type: "number",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "x",
      label: "Coordonnée X",
      description: null,
      placeholder: "Coordonnée X du magasin",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "z",
      label: "Coordonnée Z",
      description: null,
      placeholder: "Coordonnée Z du magasin",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "localisation",
      label: "Localisation",
      description: null,
      placeholder: "Dimension du magasin",
      type: "localisation",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "ville_id",
      label: "Ville",
      description: "Ville dans laquelle se trouve le magasin",
      placeholder: "Ville du magasin",
      type: "villes",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "is_siege",
      label: "Ce magasin est-il le siège du commerce ?",
      description: "Un seul siège par commerce : l'ancien siège redevient un magasin.",
      placeholder: "",
      type: "radio",
      defaultValue: false,
      render: null,
      option: [
        { label: "Oui", value: "true" },
        { label: "Non", value: "false" },
      ],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "is_public",
      label: "Le magasin est-il public ?",
      description: null,
      placeholder: "",
      type: "radio",
      defaultValue: true,
      render: null,
      option: [
        { label: "Public", value: "true" },
        { label: "Privé", value: "false" },
      ],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "commerce_id",
      label: "id",
      description: "url",
      placeholder: "Commerce du magasin",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: true,
      display: false,
      param: true,
    },
  ],
  api: {
    get: { method: "GET", url: "$apiURL/commerces/magasins/id/$local-id" },
    create: { method: "POST", url: "$apiURL/commerces/magasins/create" },
    update: { method: "PUT", url: "$apiURL/commerces/magasins/update/$local-id" },
    delete: { method: "DELETE", url: "$apiURL/commerces/magasins/delete/$local-id" },
  },
  dataKey: "magasin",
  is_activate: {
    delete: true,
  },
};
