export const Config_Modal_Journal = {
  id: {
    default: "Modal",
    add: "Modal_Add_Journal",
    edit: "Modal_Edit_Journal",
  },
  title: {
    default: "Modal",
    add: "Ajouter un journal",
    edit: "Modifier un journal",
  },
  success: {
    default: "Succès",
    add: "Journal créé avec succès.",
    edit: "Journal modifié avec succès."
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de la création du journal.",
    edit: "Erreur lors de la modification du journal."
  },
  champs: [
    {
      name: "title",
      label: "Titre",
      description: null,
      placeholder: "Titre du journal",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false, 
    },
    {
      name: "author",
      label: "Auteur role-play",
      description: null,
      placeholder: "Auteur RP du journal",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "user_id",
      label: "ID de l'utilisateur",
      description: null,
      placeholder: "ID de l'utilisateur",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: true,
      display: false,
      param: true,
    },
    {
      name: "description",
      label: "Description",
      description: null,
      placeholder: "Description du journal",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "cover_color",
      label: "Couleur de la couverture",
      description: null,
      placeholder: "",
      type: "color",
      defaultValue: "#5865F2",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "published_date",
      label: "Date de publication dans le RP",
      description: null,
      placeholder: "",
      type: "date",
      defaultValue: new Date().toISOString().split("T")[0],
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
  ],
  api: {
    get: { method: "GET", url: "/api/bibliotheque/journaux/read/$id" },
    create: { method: "POST", url: "/api/bibliotheque/journaux/create" },
    update: { method: "PUT", url: "/api/bibliotheque/journaux/update/$id" },
    delete: { method: "DELETE", url: "/api/bibliotheque/journaux/delete/$id" },
  },
  dataKey: "journal",
};