export const Config_Modal_Commerce = {
  id: {
    default: "Modal",
    add: "Modal_Add_Commerce",
    edit: "Modal_Edit_Commerce",
  },
  title: {
    default: "Modal",
    add: "Créer un commerce",
    edit: "Modifier le commerce",
  },
  success: {
    default: "Succès",
    add: "Commerce créé avec succès.",
    edit: "Commerce modifié avec succès.",
    delete: "Commerce supprimé avec succès.",
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de la création du commerce.",
    edit: "Erreur lors de la modification du commerce.",
  },
  champs: [
    {
      name: "title",
      label: "Nom",
      description: null,
      placeholder: "Nom du commerce",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "description",
      label: "Description",
      description: "Activité, produits vendus, horaires… (Markdown accepté)",
      placeholder: "Description du commerce",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "is_commerce_dirigeant",
      label: "Le commerce est-il dirigeant ?",
      description: "Désactiver pour rattacher ce commerce à un commerce dirigeant (filiale, succursale…).",
      placeholder: "Sélectionner le commerce dirigeant",
      type: "commerce_dirigeant",
      defaultValue: true,
      render: null,
      option: [
        { label: "Oui" }
      ],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "is_public",
      label: "Le commerce est-il public ?",
      description: null,
      placeholder: "",
      type: "radio",
      defaultValue: true,
      render: null,
      option: [
        { label: "Public", value: "true" },
        { label: "Privé", value: "false" },
      ],
      required: false,
      display: true,
      param: false,
    },
  ],
  api: {
    get: { method: "GET", url: "$apiURL/commerces/id/$id" },
    create: { method: "POST", url: "$apiURL/commerces/create" },
    update: { method: "PUT", url: "$apiURL/commerces/update/$id" },
    delete: { method: "DELETE", url: "$apiURL/commerces/delete/$id" },
  },
  dataKey: "commerce",
  is_activate: {
    delete: true,
  },
};
