export const Config_Modal_Livre_Content_Local = {
  id: {
    default: "Modal",
    add: "Modal_Add_Livre_Content_Local_$local-id",
    edit: "Modal_Edit_Livre_Content_Local_$local-id",
  },
  title: {
    default: "Modal",
    add: "Ajouter un chapitre",
    edit: "Modifier un chapitre",
  },
  success: {
    default: "Succès",
    add: "Chapitre créé avec succès.",
    edit: "Chapitre modifié avec succès."
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de la création du chapitre.",
    edit: "Erreur lors de la modification du chapitre."
  },
  champs: [
    {
      name: "livre_id",
      label: "id",
      description: "local",
      placeholder: 0,
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: true,
      display: false,
      param: true,
    },
    {
      name: "chapitre",
      label: "Titre",
      description: null,
      placeholder: "Titre du chapitre",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false, 
    },
    {
      name: "sous_chapitre",
      label: "Sous-chapitre",
      description: null,
      placeholder: "Titre du sous-chapitre",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "ordre",
      label: "Ordre",
      description: "Ordre d'affichage du chapitre",
      placeholder: 0,
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "indent",
      label: "Indentation",
      description: "Indentation du chapitre",
      placeholder: 0,
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "content",
      label: "Contenu du chapitre",
      description: null,
      placeholder: "",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "page_number",
      label: "Numéro de page dans le livre",
      description: null,
      placeholder: "",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
  ],
  api: {
    get: { method: "GET", url: "$apiURL/bibliotheque/livres/content/read/$local-id" },
    create: { method: "POST", url: "$apiURL/bibliotheque/livres/content/create" },
    update: { method: "PUT", url: "$apiURL/bibliotheque/livres/content/update/$local-id" },
    delete: { method: "DELETE", url: "$apiURL/bibliotheque/livres/content/delete/$local-id" },
  },
  dataKey: "content",
  is_activate: {
    delete: true,
  },
};