export const Config_Modal_Religion = {
  id: {
    default: "Modal",
    add: "Modal_Add_Religion",
    edit: "Modal_Edit_Religion",
  },
  title: {
    default: "Modal",
    add: "Ajouter une religion",
    edit: "Modifier une religion",
  },
  success: {
    default: "Succès",
    add: "Religion créée avec succès.",
    edit: "Religion modifiée avec succès."
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de la création de la religion.",
    edit: "Erreur lors de la modification de la religion."
  },
  champs: [
    {
      name: "title",
      label: "Titre",
      description: null,
      placeholder: "Titre de la religion",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "description",
      label: "Description",
      description: null,
      placeholder: "Description de la religion",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "date_founded",
      label: "Date de fondation dans le RP",
      description: "",
      placeholder: "",
      type: "date",
      defaultValue: new Date().toISOString().split("T")[0],
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "is_public",
      label: "La religion est-elle publique ?",
      description: null,
      placeholder: "",
      type: "radio",
      defaultValue: true,
      render: null,
      option: [
        { label: "Public", value: "true" },
        { label: "Privé", value: "false" },
      ],
      required: false,
      display: true,
      param: false,
    },
  ],
  api: {
    get: { method: "GET", url: "$apiURL/religions/id/$id" },
    create: { method: "POST", url: "$apiURL/religions/create" },
    update: { method: "PUT", url: "$apiURL/religions/update/$id" },
    delete: { method: "DELETE", url: "$apiURL/religions/delete/$id" },
  },
  dataKey: "religion",
  is_activate: {
    delete: true,
  },
};