export const Config_Modal_Livre = {
  id: {
    default: "Modal",
    add: "Modal_Add_Livre",
    edit: "Modal_Edit_Livre",
  },
  title: {
    default: "Modal",
    add: "Ajouter un livre",
    edit: "Modifier un livre",
  },
  success: {
    default: "Succès",
    add: "Livre créé avec succès.",
    edit: "Livre modifié avec succès."
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de la création du livre.",
    edit: "Erreur lors de la modification du livre."
  },
  champs: [
    {
      name: "title",
      label: "Titre",
      description: null,
      placeholder: "Titre du livre",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false, 
    },
    {
      name: "author",
      label: "Auteur role-play",
      description: null,
      placeholder: "Auteur RP du livre",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "user_id",
      label: "ID de l'utilisateur",
      description: null,
      placeholder: "ID de l'utilisateur",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: true,
      display: false,
      param: true,
    },
    {
      name: "description",
      label: "Description",
      description: null,
      placeholder: "Description du livre",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "cover_color",
      label: "Couleur de la couverture",
      description: null,
      placeholder: "",
      type: "color",
      defaultValue: "#5865F2",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "published_date",
      label: "Date de publication dans le RP",
      description: null,
      placeholder: "",
      type: "date",
      defaultValue: new Date().toISOString().split("T")[0],
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
  ],
  api: {
    get: { method: "GET", url: "$apiURL/bibliotheque/livres/read/$id" },
    create: { method: "POST", url: "$apiURL/bibliotheque/livres/create" },
    update: { method: "PUT", url: "$apiURL/bibliotheque/livres/update/$id" },
    delete: { method: "DELETE", url: "$apiURL/bibliotheque/livres/delete/$id" },
  },
  dataKey: "livre",
  is_activate: {
    delete: true,
  },
};