export const Config_Modal_Gouvernement = {
  id: {
    default: "Modal",
    add: "Modal_Add_Gouvernement",
    edit: "Modal_Edit_Gouvernement",
  },
  title: {
    default: "Modal",
    add: "Ajouter un gouvernement",
    edit: "Modifier un gouvernement",
  },
  success: {
    default: "Succès",
    add: "Gouvernement créé avec succès.",
    edit: "Gouvernement modifié avec succès."
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de la création du gouvernement.",
    edit: "Erreur lors de la modification du gouvernement."
  },
  champs: [
    {
      name: "title",
      label: "Titre",
      description: null,
      placeholder: "Titre du gouvernement",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "description",
      label: "Description",
      description: null,
      placeholder: "Description du gouvernement",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "type",
      label: "Type de gouvernement",
      description: "",
      placeholder: "",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "civilisation_id",
      label: "Civilisation",
      description: null,
      placeholder: "Civilisation du gouvernement",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "devise",
      label: "Devise du gouvernement",
      description: null,
      placeholder: "",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "hymne",
      label: "Hymne du gouvernement",
      description: null,
      placeholder: "Hymne du gouvernement",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
  ],
  api: {
    get: { method: "GET", url: "$apiURL/civilisations/gouvernement/read/$id" },
    create: { method: "POST", url: "$apiURL/civilisations/gouvernement/create" },
    update: { method: "PUT", url: "$apiURL/civilisations/gouvernement/update/$id" },
    delete: { method: "DELETE", url: "$apiURL/civilisations/gouvernement/delete/$id" },
  },
  dataKey: "gouvernement",
  is_activate: {
    delete: false,
  },
};