export const Config_Modal_Civilisation = {
  id: {
    default: "Modal",
    add: "Modal_Add_Civilisation",
    edit: "Modal_Edit_Civilisation",
  },
  title: {
    default: "Modal",
    add: "Ajouter une civilisation",
    edit: "Modifier une civilisation",
  },
  success: {
    default: "Succès",
    add: "Civilisation créée avec succès.",
    edit: "Civilisation modifiée avec succès."
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de la création de la civilisation.",
    edit: "Erreur lors de la modification de la civilisation."
  },
  champs: [
    {
      name: "title",
      label: "Titre",
      description: null,
      placeholder: "Titre de la civilisation",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "description",
      label: "Description",
      description: null,
      placeholder: "Description de la civilisation",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "date_founded",
      label: "Date de fondation dans le RP",
      description: "",
      placeholder: "",
      type: "date",
      defaultValue: new Date().toISOString().split("T")[0],
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "gouvernement_id",
      label: "Gouvernement",
      description: null,
      placeholder: "Gouvernement de la civilisation",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "is_public",
      label: "La civilisation est-elle publique ?",
      description: null,
      placeholder: "",
      type: "radio",
      defaultValue: true,
      render: null,
      option: [
        { label: "Public", value: "true" },
        { label: "Privé", value: "false" },
      ],
      required: false,
      display: true,
      param: false,
    },
  ],
  api: {
    get: { method: "GET", url: "/api/civilisations/read/$id" },
    create: { method: "POST", url: "/api/civilisations/create" },
    update: { method: "PUT", url: "/api/civilisations/update/$id" },
    delete: { method: "DELETE", url: "/api/civilisations/delete/$id" },
  },
  dataKey: "civilisation",
};