export const Config_Modal_Ville = {
  id: {
    default: "Modal",
    add: "Modal_Add_Ville",
    edit: "Modal_Edit_Ville_$id",
  },
  title: {
    default: "Modal",
    add: "Ajouter une ville",
    edit: "Modifier une ville",
  },
  success: {
    default: "Succès",
    add: "Ville créée avec succès.",
    edit: "Ville modifiée avec succès."
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de la création de la ville.",
    edit: "Erreur lors de la modification de la ville."
  },
  champs: [
    {
      name: "title",
      label: "Titre",
      description: null,
      placeholder: "Nom de la ville",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "description",
      label: "Description",
      description: null,
      placeholder: "Description de la ville",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "population",
      label: "Population",
      description: null,
      placeholder: "Population de la ville",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "founded_date",
      label: "Date de fondation dans le RP",
      description: "",
      placeholder: "",
      type: "date",
      defaultValue: new Date().toISOString().split("T")[0],
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "dimension_id",
      label: "Dimension",
      description: null,
      placeholder: "Dimension de la ville",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "x",
      label: "Coordonnée X",
      description: null,
      placeholder: "Coordonnée X de la ville",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "z",
      label: "Coordonnée Z",
      description: null,
      placeholder: "Coordonnée Z de la ville",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "localisation",
      label: "Localisation",
      description: null,
      placeholder: "Localisation de la ville",
      type: "localisation",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "is_capital",
      label: "La ville est-elle la capitale ?",
      description: null,
      placeholder: "",
      type: "radio",
      defaultValue: true,
      render: null,
      option: [
        { label: "Oui", value: "true" },
        { label: "Non", value: "false" },
      ],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "is_public",
      label: "La ville est-elle publique ?",
      description: null,
      placeholder: "",
      type: "radio",
      defaultValue: true,
      render: null,
      option: [
        { label: "Publique", value: "true" },
        { label: "Privée", value: "false" },
      ],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "civilisation_id",
      label: "id",
      description: "url",
      placeholder: "Civilisation de la ville",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: true,
      display: false,
      param: true,
    },
  ],
  api: {
    get: { method: "GET", url: "$apiURL/civilisations/villes/id/$id" },
    create: { method: "POST", url: "$apiURL/civilisations/villes/create" },
    update: { method: "PUT", url: "$apiURL/civilisations/villes/update/$id" },
    delete: { method: "DELETE", url: "$apiURL/civilisations/villes/delete/$id" },
  },
  dataKey: "ville",
  is_activate: {
    delete: true,
  },
};