export const ModalCivilisationAddConfig = {
  id: "CivilisationAddModal",
  title: "Ajouter une civilisation",
  champs: [
    {
      name: "title",
      label: "Titre",
      description: null,
      placeholder: "Titre de la civilisation",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "description",
      label: "Description",
      description: null,
      placeholder: "Description de la civilisation",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "date_founded",
      label: "Date de fondation dans le RP",
      description: "",
      placeholder: "",
      type: "date",
      defaultValue: new Date().toISOString().split("T")[0],
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "gouvernement_id",
      label: "Gouvernement",
      description: null,
      placeholder: "Gouvernement de la civilisation",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "is_public",
      label: "La civilisation est-elle publique ?",
      description: null,
      placeholder: "",
      type: "radio",
      defaultValue: true,
      render: null,
      option: [
        { label: "Public", value: "true" },
        { label: "Privé", value: "false" },
      ],
      required: false,
      display: true,
      param: false,
    },
  ],
  api: "/api/civilisations/create",
  success: { text: "Civilisation créée avec succès." },
  error: { text: "Erreur lors de la création de la civilisation." },
};