export const ModalJournalAddConfig = {
  id: "JournalAddModal",
  title: "Ajouter un journal",
  champs: [
    {
      name: "title",
      label: "Titre",
      description: null,
      placeholder: "Titre du journal",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false, 
    },
    {
      name: "author",
      label: "Auteur",
      description: null,
      placeholder: "Auteur du journal",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "user_id",
      label: "ID de l'utilisateur",
      description: null,
      placeholder: "ID de l'utilisateur",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: true,
      display: false,
      param: true,
    },
    {
      name: "description",
      label: "Description",
      description: null,
      placeholder: "Description du journal",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "cover_color",
      label: "Couleur de la couverture",
      description: null,
      placeholder: "",
      type: "color",
      defaultValue: "#5865F2",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "published_date",
      label: "Date de publication dans le RP",
      description: null,
      placeholder: "",
      type: "date",
      defaultValue: new Date().toISOString().split("T")[0],
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
  ],
  api: "/api/bibliotheque/journaux/create",
  success: { text: "Journal créé avec succès." },
  error: { text: "Erreur lors de la création du journal." },
};