export const quartierModal = {
  id: {
    default: "Modal",
    add: "Modal_Add_Quartier",
    edit: "Modal_Edit_Quartier",
  },
  title: {
    default: "Modal",
    add: "Ajouter un quartier",
    edit: "Modifier le quartier",
  },
  success: {
    default: "Succès",
    add: "Quartier créé avec succès.",
    edit: "Quartier modifié avec succès.",
    delete: "Quartier supprimé avec succès.",
  },
  error: {
    default: "Erreur",
    add: "Erreur lors de la création du quartier.",
    edit: "Erreur lors de la modification du quartier.",
  },
  champs: [
    {
      name: "title",
      label: "Nom",
      description: null,
      placeholder: "Nom du quartier",
      type: "text",
      defaultValue: "",
      render: null,
      option: [],
      required: true,
      display: true,
      param: false,
    },
    {
      name: "description",
      label: "Description",
      description: "Ambiance, bâtiments remarquables, habitants… (Markdown accepté)",
      placeholder: "Description du quartier",
      type: "textarea",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "population",
      label: "Population",
      description: null,
      placeholder: "Nombre d'habitants",
      type: "number",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: false,
      param: false,
    },
    {
      name: "founded_date",
      label: "Date de fondation dans le RP",
      description: "",
      placeholder: "",
      type: "date",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "localisation",
      label: "Coordonnée du centre",
      description: "Centre du quartier. Laisser vide pour le placer au centre de la ville.",
      placeholder: "",
      type: "localisation",
      defaultValue: "",
      render: null,
      option: [],
      required: false,
      display: true,
      param: false,
    },
    {
      name: "is_public",
      label: "Le quartier est-il public ?",
      description: null,
      placeholder: "",
      type: "radio",
      defaultValue: true,
      render: null,
      option: [
        { label: "Public", value: "true" },
        { label: "Privé", value: "false" },
      ],
      required: true,
      display: true,
      param: false,
    },
    {
      // Ajout depuis la page d'une ville : la ville vient de l'URL (/civilisation/:civ_id/ville/:id)
      name: "ville_id",
      label: "id",
      description: "url",
      placeholder: "",
      type: "number",
      defaultValue: 0,
      render: null,
      option: [],
      required: true,
      display: false,
      param: true,
    },
  ],
  api: {
    get: { method: "GET", url: "$apiURL/civilisations/quartiers/id/$id" },
    create: { method: "POST", url: "$apiURL/civilisations/quartiers/create" },
    update: { method: "PUT", url: "$apiURL/civilisations/quartiers/update/$id" },
    // L'API attend l'identifiant en paramètre de requête (DELETE /quartiers/delete?QuartierID=…)
    delete: { method: "DELETE", url: "$apiURL/civilisations/quartiers/delete?QuartierID=$id" },
  },
  dataKey: "quartier",
  is_activate: {
    delete: true,
  },
};
